backend:
  name: github
  repo: LhiLhiLhi/Vlog
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "diario"
    label: "Entradas del Diario"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Cuerpo del Texto", name: "body", widget: "text"}
